services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: spr-web
        restart: unless-stopped
        ports:
            - "${PORT:-3008}:3008"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.spr-web.rule=Host(`145.79.15.106`)"
            - "traefik.http.routers.spr-web.entrypoints=web,websecure"
            - "traefik.http.services.spr-web.loadbalancer.server.port=3008"
            - "traefik.http.routers.spr-web.tls=true"
            - "traefik.http.routers.spr-web.tls.certresolver=mytlschallenge"
        networks:
            - root_default
        environment:
            NODE_ENV: production
            PORT: 3008

networks:
    root_default:
        external: true
